AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: go-serverless-lambda-apigw-offline-skeleton
Resources:
  graphql:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/graphql/bin/graphql
      Runtime: go1.x
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
  playground:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/playground/handler.playgroundHandler
      Runtime: nodejs8.10
      Environment:
        Variables:
          APP_GRAPHQL_ENDPOINT: /graphql
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /playground
            Method: get
